

version: '3.9'

services:
  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: adv_rest_api

    networks:
      dev_network:
        aliases:
          - db-main


